{
  "logurl": "http://my-log.mozilla.org/adjacent_identic_failure_lines.txt.gz",
  "errors": [
    {
      "linenumber": 1610,
      "line": "14:04:50     INFO -  /data/local/tmp/test_root/tests/tests/tests/gc/weak-marking-01.js:141:11 Error: Assertion failed: got 4, expected 5"
    },
    {
      "linenumber": 1619,
      "line": "14:04:50  WARNING -  TEST-UNEXPECTED-FAIL | tests/jit-test/jit-test/tests/gc/weak-marking-01.js | obj2,obj3 (code 3, args \"\") [0.3 s]"
    },
    {
      "linenumber": 1623,
      "line": "14:04:50     INFO -  INFO stdout          > /data/local/tmp/test_root/tests/tests/tests/gc/weak-marking-01.js:141:11 Error: Assertion failed: got 4, expected 5"
    },
    {
      "linenumber": 1628,
      "line": "14:04:50     INFO -  INFO stderr         2> /data/local/tmp/test_root/tests/tests/tests/gc/weak-marking-01.js:141:11 Error: Assertion failed: got 4, expected 5"
    },
    {
      "linenumber": 1633,
      "line": "14:04:50     INFO -  /data/local/tmp/test_root/tests/tests/tests/gc/weak-marking-01.js:141:11 Error: Assertion failed: got 4, expected 5"
    },
    {
      "linenumber": 1642,
      "line": "14:04:50  WARNING -  TEST-UNEXPECTED-FAIL | tests/jit-test/jit-test/tests/gc/weak-marking-01.js | obj2,obj3 (code 3, args \"--ion-eager --ion-offthread-compile=off --more-compartments\") [0.4 s]"
    },
    {
      "linenumber": 1646,
      "line": "14:04:50     INFO -  INFO stdout          > /data/local/tmp/test_root/tests/tests/tests/gc/weak-marking-01.js:141:11 Error: Assertion failed: got 4, expected 5"
    },
    {
      "linenumber": 1651,
      "line": "14:04:50     INFO -  INFO stderr         2> /data/local/tmp/test_root/tests/tests/tests/gc/weak-marking-01.js:141:11 Error: Assertion failed: got 4, expected 5"
    },
    {
      "linenumber": 1658,
      "line": "14:04:52     INFO -  /data/local/tmp/test_root/tests/tests/tests/gc/weak-marking-01.js:141:11 Error: Assertion failed: got 4, expected 5"
    },
    {
      "linenumber": 1667,
      "line": "14:04:52  WARNING -  TEST-UNEXPECTED-FAIL | tests/jit-test/jit-test/tests/gc/weak-marking-01.js | obj2,obj3 (code 3, args \"--no-blinterp --no-baseline --no-ion --more-compartments\") [0.3 s]"
    },
    {
      "linenumber": 1671,
      "line": "14:04:52     INFO -  INFO stdout          > /data/local/tmp/test_root/tests/tests/tests/gc/weak-marking-01.js:141:11 Error: Assertion failed: got 4, expected 5"
    },
    {
      "linenumber": 1676,
      "line": "14:04:52     INFO -  INFO stderr         2> /data/local/tmp/test_root/tests/tests/tests/gc/weak-marking-01.js:141:11 Error: Assertion failed: got 4, expected 5"
    },
    {
      "linenumber": 1692,
      "line": "14:04:52  WARNING -  TEST-UNEXPECTED-FAIL | tests/jit-test/jit-test/tests/gc/weak-marking-01.js | obj2,obj3 (code 3, args \"--blinterp-eager\") [0.4 s]"
    },
    {
      "linenumber": 5564,
      "line": "14:30:48    ERROR - Return code: 2"
    },
    {
      "linenumber": 6204,
      "line": "[taskcluster:error] exit status 1"
    }
  ]
}
