{
  "step_data": {
    "steps": [
      {
        "errors": [],
        "name": "set props: revision",
        "started": "2013-06-05 12:51:48.767751",
        "started_linenumber": 8,
        "finished_linenumber": 10,
        "finished": "2013-06-05 12:51:48.768393",
        "result": "success"
      },
      {
        "errors": [],
        "name": "set props: who",
        "started": "2013-06-05 12:51:48.768881",
        "started_linenumber": 12,
        "finished_linenumber": 14,
        "finished": "2013-06-05 12:51:48.769473",
        "result": "success"
      },
      {
        "errors": [
          {
            "line": "TEST-UNEXPECTED-FAIL | automation.py | application timed out after 60 seconds with no output",
            "linenumber": 24728
          },
          {
            "line": "command timed out: 1200 seconds without output",
            "linenumber": 24730
          },
          {
            "line": "buildbot.slave.commands.TimeoutError: command timed out: 1200 seconds without output",
            "linenumber": 24734
          }
        ],
        "name": "'python mochitest/runtests.py ...' warnings",
        "started": "2013-06-05 12:54:55.232364",
        "started_linenumber": 16,
        "finished_linenumber": 24982,
        "finished": "2013-06-05 13:15:39.235146",
        "result": "testfailed"
      },
      {
        "errors": [],
        "name": "'rm -rf ...'",
        "started": "2013-06-05 13:15:39.244545",
        "started_linenumber": 24984,
        "finished_linenumber": 25028,
        "finished": "2013-06-05 13:16:04.014823",
        "result": "success"
      },
      {
        "errors": [],
        "name": "maybe rebooting slave lost",
        "started": "2013-06-05 13:16:04.015405",
        "started_linenumber": 25030,
        "finished_linenumber": 25032,
        "finished": "2013-06-05 13:16:04.963614",
        "result": "success"
      }
    ],
    "errors_truncated": false
  },
  "logurl": "http://my-log.mozilla.org/reftest-timeout.txt.gz"
}
